### ISSUE TITLE
Your documentation links are hardcoded to the "master" repo

### ISSUE THREAD

**Issue by ftrotter** [Aluriak/PowerGrASP#21]
So most of them do not work... it does not seem like there is a "master" repo any more...

It would be nice if you could turn the input formats into links... I have no idea what "ASP atoms edge/2" means...

Facinating project, thanks for putting it out in the open!!
-FT

**Comment by Aluriak** [comment]
I've updated hardcoded links to stable branch 0.4.x, and added [links to example of inputs](https://github.com/Aluriak/PowerGrASP#input-file).

Can you provide your needs as input format ? Currently, the main ones are related to the biology world (SBML), my needs (edge/2) or standard (GML).

An ASP input could be the following:

    edge(a,b).
    edge(a,c).

Describing a graph where a node `a` is linked to both nodes `b` and `c`. You can find many more examples in the [`tests/` directory](https://github.com/Aluriak/PowerGrASP/tree/dev/powergrasp/tests).

Publication related to this repository is on the way, README will be updated when needed.

Thank you for pointing these problems/questions to us !

**Comment by ftrotter** [comment]
Is there not a way to make the ReadMe's into relative links? So that they simply reference into the current repo? It seems fruitless to have to update this every time you change the structure of your project.

As for my requirements, I am working with D3 Force Directed json format or GraphML or raw SQL. I would be happy to try and contribute importers for them, but it is not clear where that happens, or what I should conform to for that. Python is not my native language. 

I am hoping to use your library to sort out some very tangled graphs of within social network analysis. 

Regards,
-FT

**Comment by Aluriak** [comment]
AFAIK, there is no possible way to do that, despite its obvious interest :(

If you provides some examples of input data, i can give you a script that convert it to input format, maybe integrate it to powergrasp.
Note that a simple regex preprocessing could suffice if the raw SQL describes edges.

I've integrated graphml in available input formats, so next version of powergrasp should includes it. Note that some advanced features of this format are not handled, including hypergraph. (see 574ad7ce6199e4aa7444fc7e80e97336cf0d9bcc for the handler implementation)

Documentation about *converter* is not written yet, that's could be a good doc improvement to add something quickly.

Your analysis could profit from PowerGraph Analysis, especially with tangled data.
Some performance improvements are on the way, in order to manage graph of 1000+ edges on regular machines.

**Comment by Aluriak** [comment]
There is in fact a very simple way to link to internal repository files: just gives the path :)
Documentation is now fixed !
